### ISSUE TITLE
In the POC for "CreateToken" The driver not load in Win Server 2016 UP+

### ISSUE THREAD

**Issue by Az0x00** [daem0nc0re/VectorKernel#2]
Hi on Win11 it work as you showing but in older versions it not loading the driver.

it seems it not able to create the token, propbly about finding the address of "ZwCreateToken"

i get this error=
System error 127 has occurred.
The specified procedure could not be found.

**Comment by daem0nc0re** [comment]
Hi.
Thanks for raising issue.

`ZwCreateToken` finding procedure highly depends on byte pattern, so it is a expected issue, and I didn't test older Windows.
I will handle your issue, but I'm busy these days so it will take a little time.
I will check it in a few weeks and reply here again.

**Comment by daem0nc0re** [comment]
I understood your issue.
The reason is that `CreateTokenDrv` uses `ExAllocatePool2` API.
As I wrote in [READMEmd for this repository](https://github.com/daem0nc0re/VectorKernel/blob/main/README.md), if you want to try `ExAllocatePool2` API using modules in older Windows OSes (before 2004), you must change API to `ExAllocatePoolWithTag` by yourself.
For example,
```
pInfoBuffer = ::ExAllocatePool2(POOL_FLAG_NON_PAGED, nInfoLength, (ULONG)DRIVER_TAG);
```
must be
```
pInfoBuffer = ::ExAllocatePoolWithTag(NonPagedPool, nInfoLength, (ULONG)DRIVER_TAG);
```
for old Windows OS.

**Comment by daem0nc0re** [comment]
Did you  confirm all API calls were changed?

**Comment by Az0x00** [comment]
sorry my bad...
Thanks bro !!! 💪💪💪

	pTokenGroups = (PTOKEN_GROUPS)::ExAllocatePoolWithTag(
		NonPagedPool,
		FIELD_OFFSET(TOKEN_GROUPS, Groups) + (sizeof(SID_AND_ATTRIBUTES) * 7),
		(ULONG)DRIVER_TAG);

	pTokenPrivileges = (PTOKEN_PRIVILEGES)::ExAllocatePoolWithTag(
		NonPagedPool,
		FIELD_OFFSET(TOKEN_PRIVILEGES, Privileges) + (sizeof(LUID_AND_ATTRIBUTES) * 35),
		(ULONG)DRIVER_TAG);

	pDefaultDacl = (PACL)::ExAllocatePoolWithTag(
